// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SqliteBatchDelete;

#nullable disable

namespace SqliteBatchDelete.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20211208183429_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("SqliteBatchDelete.MyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("MyUintId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MyDbSet");
                });
#pragma warning restore 612, 618
        }
    }
}
